[theme]
base = "dark"
primaryColor = "#f97316"
backgroundColor = "#080c14"
secondaryBackgroundColor = "#0d1220"
textColor = "#e2e8f0"
font = "monospace"

[server]
maxUploadSize = 500
enableXsrfProtection = false

[browser]
gatherUsageStats = false
